Add Android Debug Database library
When the dependency:

debugImplementation 'com.amitshekhar.android:debug-db:1.0.4'

was added, the following error was triggered:

error: SpotRoomDatabase_Impl is not abstract and does not override
abstract method clearAllTables() in RoomDatabase

So, I overrode the method but left it blank.